#	$gate: Makefile,v 1.1 2010/12/14 02:43:05 dukzcry Exp $
#	$OpenBSD: src/lib/libutil/Makefile,v 1.33 2010/11/17 10:10:31 jsing Exp $
#	$NetBSD: Makefile,v 1.8 1996/05/16 07:03:28 thorpej Exp $

LIB=	fakeutil
WANTLINT=

HDRS=	imsg.h
SRCS=	imsg.c imsg-buffer.c 

.include <bsd.lib.mk>
